### ISSUE TITLE
V4: Line Fields inside of structures no longer work

### ISSUE THREAD

**Issue by georgobermayr** [k-next/kirby#5938] opened 2023-11-08 08:21 UTC
## Description
I have a structure field with line fields inside of the structure. When I try to create a new structure item in the Panel, the structure is not opening, but instead throwing a JS error in the console.

**Expected behavior**  
The structure element should open and be editable. 

## To reproduce
1. Create a blueprint with a structure field and a line field inside of it:
```
fields:
  cards:
    label: Cards
    type: structure
    fields:
      test_test:
        type: text
      line_1:
        type: line
```
2. Open the page in the Panel and try to add a new structure item.
3. The structure is not opening, instead in the browser console it is logged:
```
index.min.js:1 TypeError: Cannot read properties of undefined (reading 'value')
    at Pr (index.min.js:1:348375)
    at Object.form (index.min.js:1:348564)
    at a.add (index.min.js:1:197314)
    at click (index.min.js:1:200933)
    at dn (vue.min.js:11:21974)
    at a.r (vue.min.js:11:10396)
    at dn (vue.min.js:11:21974)
    at t.$emit (vue.min.js:11:44375)
    at a.onClick (index.min.js:1:280404)
    at dn (vue.min.js:11:21974)
```
With the error being in 
```
    const e = window.panel.app.$options.components[`k-${t.type}-field`]
      , i = null == e ? void 0 : e.options.props.value;
```

## Your setup
**Kirby Version**  
Kirby 4 Beta 3

**Comment by afbora** [comment] 2023-11-08 08:30
This is duplicate of https://github.com/getkirby/kirby/issues/5931 and fixed in RC.1. So will be available next release.

**Closed as not planned by afbora** 2023-11-08 08:30 UTC
