### ISSUE TITLE
Link Field: Error message on selecting file type

### ISSUE THREAD

**Issue by plain-solutions-gmbh** [k-next/kirby#5293] opened 2023-06-16 18:02 UTC
## Description
In the link field: If i select the link type to file, there's an error coming up:

**Expected behavior**  
List of files should be appear.

**Screenshots**  
<img width="350" alt="Bildschirmfoto 2023-06-16 um 20 01 51" src="https://github.com/getkirby/kirby/assets/4754476/49c713fe-6eef-4021-a75f-dd32045fe485">

## To reproduce
1. Clone the starter kit
2. Create a link-field
3. Go to panel and select the links type to file

## Your setup
**Kirby Version**  
4.0-alpha.3

**Console output**  
(No console output)

**Your system (please complete the following information)**
 - Device: Desktop
 - OS: MacOS
 - Browser: Brave

**Comment by distantnative** [comment] 2023-06-16 18:07
Duplicate of https://github.com/getkirby/kirby/issues/5280

**Closed as not planned by distantnative** 2023-06-16 18:07 UTC
