### ISSUE TITLE
[Panel] Changing page url removes writer field

### ISSUE THREAD

**Issue by bensanlau** [k-next/kirby#6351] opened 2024-03-20 11:20 UTC
## Description

https://github.com/getkirby/kirby/assets/53568912/164a38d7-419c-4194-9266-7ad05924603e

Both fields (Standfirst and Main) are writer fields, but only the second (last?) field gets affected.

However, when I revert the changes, my content returns, but the Page Title & URL remains changed.

## Your setup
**Kirby Version**  
4.1.2

**Comment by afbora** [comment] 2024-03-20 11:56
I can't reproduce the issue. Do you have any hook or plugin?

**Comment by bastianallgeier** [comment] 2024-03-20 11:59
This is a duplicate of https://github.com/getkirby/kirby/issues/5659

@bensanlau how do you run Kirby? MAMP, Herd, built-in PHP server, etc.?

**Closed as completed by bastianallgeier** 2024-03-20 11:59 UTC
Labels: needs: replication 🔬

**Comment by bensanlau** [comment] 2024-03-20 12:46
@bastianallgeier It's built-in PHP server on macOS. 
Running php 8.2.15
macOS 14.1.1
Chrome 122.0.6261.129

Plugins installed: KQL and [Kirby Headless](https://github.com/johannschopplich/kirby-headless)

**Comment by bastianallgeier** [comment] 2024-03-20 13:39
Ok, it really seems to be connected to the PHP server in some weird way. Do you have something else available to test it locally. We can really recommend Herd or DDEV, but MAMP works well too.

**Comment by tan3ot** [comment] 2024-06-17 11:45
I can reproduce this issue.

The last writer field (which is not empty) gets emptied by changing the url.
When using blueprint columns this happens for every column.

Weird: When using tabs sometimes only the last field of the first column gets emptied.

In local dev environment  and on web server, too.
With a current project as well es a fresh starterkit.

Kirby 4.2.0
PHP 8.3
Plugins (current project):
- kirby-auto-file-templates
- kirby-fingerprint
- kirby-modules

Screenvideo 1: Columns

https://github.com/getkirby/kirby/assets/37336796/951fdda4-35cc-489d-9d8b-cf36184d2a63

Screenvideo 2: Tabs (second tab without columns)

https://github.com/getkirby/kirby/assets/37336796/59da7d18-da8a-482c-a621-da2cb832bb13
