### ISSUE TITLE
Duplicated pages with copy files enabled still links to original files UUID

### ISSUE THREAD

**Issue by timkinali** [k-next/kirby#6403] opened 2024-04-18 17:40 UTC
## Description
In the panel, when duplicating a page with “copy files” option enabled, files are indeed copied – but the page content still refers to the file UUIDs of the original page and not the ones copied over to the new page. This is a very confusing editor experience and sometimes quite messy to fix after you realise it. 

**Expected behavior**  
When duplicating a page and actively choosing to also copy the files, I expect a "clean copy" without no references to the original files. All referenced UUIDS in the content txt should be updated to refer to the copied files.  

(In case we actually _do_ want files to be referenced from the original page, we can choose to _not_ copy files. )

**Why is this an issue?**  
If the editor for example click on an image on the duplicated page and change anything in the image view, this will reflect on both the original and the duplicated page which might not be desired. 

Furthermore clicking the cogwheel on choosing "replace image", will unexpectedely change the image on both pages. 

Additionally, sometimes we duplicate a page to do some big updates (in lack of any other option). When done, we delete the original page and publish the duplicate in it's place. This means the images and other files are now missing from the duplicate as the content refers to the original files UUID. Panic moment! (Until you realise that the files is actually there in the folder, but you have to manually readd/replace them in the content. )  

## To reproduce

1. Duplicate a page
2. Enable "copy files" in the modal
3. In your code editor, compare the UUIDs referenced in the duplicated page txt file with the copied files UUIDs, and see that they do not match. Optionally, on the duplicated page in the panel, just click on a file and check the files breadcrumb to understand that the file does not live on the current page.
 
## Your setup
**Kirby Version**  
Kirby 4.2
PHP 8.2

**Comment by texnixe** [comment] 2024-04-18 17:50
Duplicate of https://github.com/getkirby/kirby/issues/4867

**Closed as not planned** 2024-04-18 18:18 UTC
