### ISSUE TITLE
[v4] Navigating through the link field inside a structure always show the dropdown as url, it does not update to the correct "type"

### ISSUE THREAD

**Issue by wdebusschere** [k-next/kirby#5814] opened 2023-10-18 10:38 UTC
## Description
Navigating through the link field inside a structure always show the dropdown as url, it does not update to the correct "type": ex. page, file,...
Editing a link directly by clicking on the link itself in the structure table works!

**Expected behavior**  
Correct link type Page for example.

**Screenshots**  

![Screenshot 2023-10-18 at 11 35 59](https://github.com/getkirby/kirby/assets/4136426/5ed499d4-79b5-4ab1-b1c0-095d32a7e59a)

## To reproduce
1. Create a structure with the link field
2. Add multiple links to the structure.
3. Navigate with the next arrow to the next link and if it's a page, the dropdown is still url

## Your setup
**Kirby Version**  
4.0.0-beta.2

**Comment by afbora** [comment] 2023-10-18 10:53
I can't reproduce the issue. My tested blueprint is:

````yaml
fields:          
  structure:
    type: structure
    fields:
      link:
        type: link
````

**Comment by wdebusschere** [comment] 2023-10-18 10:58
@afbora 

Add 3 links of 3 different types (page, url, file).
Then click on 1 of them on the table, and navigate to the next one.

Example click on the page link, then go to the next link = url, the dropdown is still page..


![Screenshot 2023-10-18 at 11 58 34](https://github.com/getkirby/kirby/assets/4136426/86636560-3e7b-48bd-8498-9c49605eed66)

**Comment by afbora** [comment] 2023-10-18 11:07
Oh, I can reproduce the issue with different types. But I also good news that this issue seems fixed in beta.3. You can test beta.3 here [kirby.zip](https://github.com/getkirby/kirby/files/13015500/kirby.zip)

Please let me know if you've still have the issue.

**Closed as completed by afbora** 2023-10-18 11:07 UTC
