### ISSUE TITLE
Tags field loses content when saving

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#4590] opened 2022-08-19 09:54 UTC
## Description
When saving the page directly after typing some text, the tags field will disregard the input. You have to blur the field or press enter to actually trigger a change.

**Expected behavior**  
The field should not lose content.

**Screenshots**  

![tags](https://user-images.githubusercontent.com/7975568/185593485-fd2cad8a-c4de-4a0b-845e-866c5f206c16.gif)

## To reproduce

1. Add a tags field to your blueprint
2. Enter some text
3. Hit ⌘S or Ctrl + S depending on your OS

## Your setup
**Kirby Version**  
3.7.4-rc.1

**Comment by distantnative** [comment] 2022-08-19 11:27
`TagsInput.vue` will need something like this:

```js
// make sure to commit input value when Cmd+S is hit
this.$events.$on("keydown.cmd.s", this.onBlur);
```

Should be relatively easy to fix.

**Comment by lukasbestle** [comment] 2022-08-21 16:34
@distantnative I suggest we move this to 3.8.0 because there will not be another RC before the release of 3.7.4.

**Comment by distantnative** [comment] 2022-08-21 17:03
@lukasbestle I have added a potential fix https://github.com/getkirby/kirby/commit/f5238795a1ca5be6c29234eb7e76c178fa2e092b - what do you think?

**Comment by distantnative** [comment] 2022-08-21 17:04
sure

**Comment by distantnative** [comment] 2022-08-21 19:40
It's also not as easy as I thought. We actually already listen to the keyboard shortcut - but what seems to happen is a race condition, where the watcher receives the old input again and updates the local data before the newly committed value has been emitted.

**Comment by trych** [comment] 2022-09-12 14:24
Maybe I add this to the same issue, as this is closely related. When enter some comma separated tags and then instead of hitting enter, I click outside the field, the tags will visually show as one big, merged tag:

![Bildschirmfoto 2022-09-12 um 16 22 27](https://user-images.githubusercontent.com/9803905/189678783-89786c2d-c1d4-421b-82d7-61de58951f90.png)

They are correctly saved to the content file though and when I leave the page and then navigate back to it, they show correctly again:

![Bildschirmfoto 2022-09-12 um 16 23 20](https://user-images.githubusercontent.com/9803905/189679011-7bafe879-75f8-4458-9084-418883853fb4.png)

When I hit enter in the tag field, the tags are separated correctly directly.

**Comment by distantnative** [comment] 2022-09-13 18:17
@trych moved this to its own issue as it's not caused by the same code (yours is much easier to fix)

**Comment by bastianallgeier** [comment] 2022-09-19 09:38
✅

**Closed as completed by bastianallgeier** 2022-09-19 09:38 UTC
