### ISSUE TITLE
[v4] Link Field directs to wrong language in multi-language setup

### ISSUE THREAD

**Issue by vibellio** [k-next/kirby#5903] opened 2023-11-02 15:32 UTC
## Description
**important: default language is german (de)**

when the frontend is visited in e.g. english under `example.com/en` and the user clicks a link (generated from the new link field), he is moved to `example.com/de/was-auch-immer-die-url-ist`

so he will be directed to the wrong translation of the page - in this case the page directs always to the default language.
also the url ist not printed absolute, it's printed like this:

`<a href="/@/page/hgRfTPNopQOfxrPk">Contact</a>`

**Expected behavior**  
directing to the correct translated version of the linked page and printing the absolute url of the linked page

## Your setup
4.0.0-beta.2

**Your system (please complete the following information)**
 - Device: MacBook Pro M2 Pro (2023)
 - OS: macOS 14.1 
 - Browser: Chromium Engine 
 - Version: 118.0.5993.70

**Comment by distantnative** [comment] 2023-11-02 15:36
Thank you, this is a duplicate of/related to https://github.com/getkirby/kirby/issues/5551

**Closed as not planned by distantnative** 2023-11-02 15:36 UTC
