### ISSUE TITLE
Failing Test for DateTest

### ISSUE THREAD

**Issue by SeriousKen** [k-next/kirby#6444] opened 2024-05-09 06:26 UTC
## Description

Running the test suite gives a failing test `DateTest::testToStringModeTime`.

**Expected behavior**  

Test should pass.

**Result**

2) Kirby\Toolkit\DateTest::testToStringModeTime
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'12:12:12+00:00'
+'12:12:12+01:00'

## To reproduce

1. Clone repository
2. Run the test suite `phpunit`
3. See error

## Your setup
**Kirby Version**  

4.2.0

**Console output**  

**Your system (please complete the following information)**
 - Device:  Dell Inspiron Laptop
 - OS:  Ubuntu 20.04 on WSL2 Windows 11
 - Browser:  N/A
 - Version:  N/A

**Additional context**  

I am in the UK which is currently in BST which is +01:00

**Comment by distantnative** [comment] 2024-07-22 07:44
@SeriousKen I cannot reproduce this. Even in a very different timezone (was recently in South Korea), the tests all run through for me.

**Comment by distantnative** [comment] 2024-09-14 09:31
Closing this, please let us know if you know a way to reproduce it.

**Closed as not planned by distantnative** 2024-09-14 09:31 UTC
Labels: needs: replication 🔬
