### ISSUE TITLE
Random logouts while using the Panel

### ISSUE THREAD

**Issue by Moucky** [k-next/kirby#3981] opened 2021-12-02 05:44 UTC
**Describe the bug**  
I am logged out of the panel when I try to click though to the file(an image) from the image field. The image is uploading successfully and displaying on the frontend. The PHP logs seem to show a 302 error every time I try to access the file page.

Working locally using Nginx on Docker.

**Kirby Version**  
3.6.0

**PHP Version** 
8.0.13

**Server**
Apache

**Comment by afbora** [comment] 2021-12-02 07:18
I can't test in Nginx/Docker but I couldn't reproduce the issue on my Windows local.

Do you have the same problem in starterkit or plainkit? Are you using any plugin?

**Comment by Moucky** [comment] 2021-12-06 01:07
I just tried removing all plugins and added the plainkit files and the problem remains. I think this is bound to be a server configuration issue but I'm not sure what. The permissions seem to be fine.

It's the first time I've used Kirby 3.6.0 and PHP 8.0.13 and haven't had this problem before. The PHP version locally on Docker is 7.4.15 but if it's working OK for you then I doubt it's the PHP or Kirby versions.

**Comment by Moucky** [comment] 2021-12-06 23:11
Strangely I am now being logged out of the panel on my localhost environment, not when browsing to a file page but seemingly at random. I have deleted all the browser(Chrome) cookies and also the Kirby session files. When I use an incognito tab I don't have the problem. I have never experienced this with Kirby before.

**Comment by hannesherold** [comment] 2021-12-19 12:31
I have a similar issue, it happens extremely irregularly. The panel logs out often and in quick succession. On another day, the phenomenon seems not to occur with the same setup. I have not been able to find a reason or pattern. However, I have not done any systematic tests so far.

Kirby 3.6.0 and 3.6.1.1 
latest Opera and Firefox
macOS Monterey 12.0.1
Laravel Valet
PHP 7.4.24
Codekit 3.15.1

My usual setup in development is that in one tab the frontend runs through Codekit, and Codekit takes care of hot browser refresh (`http://localhost:5757`). In the other tab, the panel runs without Codekit (`http://myproject.test`). 

My suspicion was that the cause could be Codekit. But just now as I am writing this post, my project has logged out again. I turned off Codekit completely and logged into the panel again, but a short time later I was kicked out once more.

Something still goes wrong with Codekit since Kirby 3.6., though: When the panel runs through the Codekit server, this error occurs on login:

> Failed to execute 'replaceState' on 'History': A history state object
> with URL '`http://myproject.test/panel/site`' cannot be created in a
> document with origin '`http://localhost:5757`' and URL
> '`http://localhost:5757/panel/login`'.

However, the login itself works. Despite the error message, the dashboard can be accessed after that via the direct link: `http://localhost:5757/panel/site`

On logout, the same error occurs again (Failed to execute 'replaceState' on 'History':).

Edit: I can't make any sense of it. Now the automatic-logout-phenomenon hasn't occurred for over two hours, Codekit is running, and I'm logged into the panel of several different Kirby instances in different browser tabs simultaneously – including the project I was kicked out of before. :thinking:

**Comment by distantnative** [comment] 2021-12-19 12:35
Might be that the `replaceState` error is just something separate, but if it's connected to your main problem, @hannesherold, could it be that using the backward/forward buttons in your browser lead to the log-out?

**Comment by hannesherold** [comment] 2021-12-19 12:42
> Might be that the `replaceState` error is just something separate, but if it's connected to your main problem, @hannesherold, could it be that using the backward/forward buttons in your browser lead to the log-out?

I don't know if it's connected. I tend to suspect not, because the panel doesn't normally go through the codekit server.

The bug occurs regardless of backward/forward, also when the tab or even the browser is not in focus. The panel also logs off in the background.

**Comment by lukasbestle** [comment] 2021-12-19 12:54
I've seen another comment somewhere that was related to multiple browser windows/tabs or multiple users working in parallel. The same could be happening here because of the second tab that goes through Codekit.

@hannesherold After you stopped Codekit, did you also have more than one Panel tab open or just one?

**Comment by hannesherold** [comment] 2021-12-19 13:11
> After you stopped Codekit, did you also have more than one Panel tab open or just one?

I think it was just one. 

At the moment I cannot reproduce the error. There are several projects running in parallel, including a plainkit, all panels logged in. I turn Codekit on and off, reload, go back and forth, do nothing - no logouts.

**Comment by lukasbestle** [comment] 2021-12-19 15:01
I have also opened three Panel tabs in two browsers this morning and interact with them every so often, so far without running into this. 😞

**Comment by lukasbestle** [comment] 2021-12-19 17:13
Another thing that would be interesting for context: Do you use the checkbox "Keep me logged in"?

**Comment by hannesherold** [comment] 2021-12-19 19:08
> Another thing that would be interesting for context: Do you use the checkbox "Keep me logged in"?

For my part, no, I don't.

**Comment by Moucky** [comment] 2021-12-19 19:37
I don't use  "Keep me logged in" either. The only way I seem to consistently be logged out is when I browse to a file page in the panel and only on my production server, not the local environment. I haven't been able to determine what might be causing that. I assumed it would have been a permissions issue but they all seem fine. All the other times are random logouts.

**Comment by lukasbestle** [comment] 2021-12-19 21:20
Could you please test the "Keep me logged in" option to rule out the auto-logout as a cause? If you still get logged out randomly in the middle of a work day, we know it's something else.

**Comment by foobartel** [comment] 2022-01-06 04:11
Hi, I‘m experiencing the same issue of being randomly logged out on my personal site, production on foobartel.com. The issue previously occurred in #3971. In the meantime I uninstalled the serviceworker, updated to 3.6.1 and 3.6.1.1, and somewhere along the line the issue disappeared, I can‘t remember exactly when.
 
The problem now resurfaced and it kicks me out very randomly while writing, saving or doing nothing at all. I did not see this for some time, maybe only since 3.6.1.1 again I think… It also happens for me with the "Keep me logged in" option checked.  

Kirby 3.6.1.1 
PHP 7.4.24 and 8.0.13

**Comment by lukasbestle** [comment] 2022-01-06 10:17
@foobartel Which browser and operating system?

**Comment by foobartel** [comment] 2022-01-07 04:59
This is on macOS 12.1 and Chrome 96, it happened yesterday ~ every 15 minutes. 
Upgraded to Chrome 97 today, problem disappeared. It also does not occur in Safari 15.2 on macOS.

**Comment by lukasbestle** [comment] 2022-01-08 09:59
The issue continues to be incredibly weird...

**Comment by hannesherold** [comment] 2022-01-08 11:16
> The issue continues to be incredibly weird...

Really true! Since my last posts, the phenomenon has never happened to me again. I have tried all sorts of things, different browsers, multiple tabs per window with multiple logins to the panel, "keep me logged in" or not, CodeKit actived/deactivated, even different WiFi networks – but no logouts. The panel works just as it should. 🤷

**Comment by bastianallgeier** [comment] 2022-01-11 11:39
I wonder if this could be related: https://github.com/getkirby/kirby/issues/4083

**Comment by foobartel** [comment] 2022-01-12 09:17
#4083 seems to be somewhat related to what I posted a while ago in #3508. Around that time, the log out issue also occurred as reported in #3971.

**Comment by foobartel** [comment] 2022-01-12 09:25
The below is some Console output over a few sessions of randomly getting logged out last week. 

```
index.js:1 Fetch failed loading: GET "https://foobartel.com/api/auth".
request @ index.js:1
get @ index.js:1
user @ index.js:1
setInterval (async)
onSuccess @ index.js:1
request @ index.js:1
await in request (async)
get @ index.js:1
load @ index.js:1
reload @ index.js:1
(anonymous) @ vendor.js:12
emit @ vendor.js:12
onSave @ index.js:1
await in onSave (async)
(anonymous) @ vendor.js:12
emit @ vendor.js:12
keydown @ index.js:1
index.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'querySelector')
    at a.focus (index.js:1)
    at index.js:1
focus @ index.js:1
(anonymous) @ index.js:1
setTimeout (async)
open @ index.js:1
open @ index.js:1
(anonymous) @ vendor.js:6
Ut @ vendor.js:6
Promise.then (async)
qt @ vendor.js:6
te @ vendor.js:6
t.$nextTick @ vendor.js:6
mounted @ index.js:1
Vt @ vendor.js:6
nn @ vendor.js:6
insert @ vendor.js:6
O @ vendor.js:6
(anonymous) @ vendor.js:6
t._update @ vendor.js:6
r @ vendor.js:6
vn.get @ vendor.js:6
vn.run @ vendor.js:6
dn @ vendor.js:6
(anonymous) @ vendor.js:6
Ut @ vendor.js:6
Promise.then (async)
qt @ vendor.js:6
te @ vendor.js:6
(anonymous) @ vendor.js:6
vn.update @ vendor.js:6
ct.notify @ vendor.js:6
set @ vendor.js:6
SET_DIALOG @ index.js:1
(anonymous) @ vendor.js:6
(anonymous) @ vendor.js:12
(anonymous) @ vendor.js:12
_s._withCommit @ vendor.js:12
_s.commit @ vendor.js:12
commit @ vendor.js:6
dialog @ index.js:1
(anonymous) @ vendor.js:6
_s.dispatch @ vendor.js:12
dispatch @ vendor.js:6
o.dispatch @ vendor.js:6
error @ index.js:1
(anonymous) @ vendor.js:6
_s.dispatch @ vendor.js:12
dispatch @ vendor.js:6
window.onunhandledrejection @ index.js:1
index.js:1 GET https://foobartel.com/api/auth 403
request @ index.js:1
get @ index.js:1
user @ index.js:1
setInterval (async)
onSuccess @ index.js:1
request @ index.js:1
await in request (async)
get @ index.js:1
load @ index.js:1
reload @ index.js:1
(anonymous) @ vendor.js:12
emit @ vendor.js:12
onSave @ index.js:1
await in onSave (async)
(anonymous) @ vendor.js:12
emit @ vendor.js:12
keydown @ index.js:1
index.js:1 Fetch failed loading: GET "https://foobartel.com/api/auth".
request @ index.js:1
get @ index.js:1
user @ index.js:1
setInterval (async)
onSuccess @ index.js:1
request @ index.js:1
await in request (async)
get @ index.js:1
load @ index.js:1
reload @ index.js:1
(anonymous) @ vendor.js:12
emit @ vendor.js:12
onSave @ index.js:1
await in onSave (async)
(anonymous) @ vendor.js:12
emit @ vendor.js:12
keydown @ index.js:1
index.js:1 GET https://foobartel.com/api/auth 403
request @ index.js:1
get @ index.js:1
user @ index.js:1
setInterval (async)
onSuccess @ index.js:1
request @ index.js:1
await in request (async)
get @ index.js:1
load @ index.js:1
reload @ index.js:1
(anonymous) @ vendor.js:12
emit @ vendor.js:12
onSave @ index.js:1
await in onSave (async)
(anonymous) @ vendor.js:12
emit @ vendor.js:12
keydown @ index.js:1
index.js:1 Fetch failed loading: GET "https://foobartel.com/api/auth".
request @ index.js:1
get @ index.js:1
user @ index.js:1
setInterval (async)
onSuccess @ index.js:1
request @ index.js:1
await in request (async)
get @ index.js:1
load @ index.js:1
reload @ index.js:1
(anonymous) @ vendor.js:12
emit @ vendor.js:12
onSave @ index.js:1
await in onSave (async)
(anonymous) @ vendor.js:12
emit @ vendor.js:12
keydown @ index.js:1
login:1 Autofocus processing was blocked because a document already has a focused element.
```

**Comment by Moucky** [comment] 2022-04-26 22:36
Has anyone else experienced being logged out when clicking though to the file from the image field? Because for me that will consistently log me out. Kirby version 3.6.1.1.

**Comment by lukasbestle** [comment] 2022-06-27 19:56
I have the feeling that some of the issues you have described in this thread are due to browser or intermediary caches caching things that they shouldn't. This would explain why it's so hard to reproduce these issues consistently.

In Kirby 3.7.0 we have finally revamped the caching setup. If you have issues with random logouts or session errors, I really recommend to update to 3.7.0+.

For now I'm closing this issue. If you still have problems with authentication/sessions, please add a comment below and I will reopen the issue.

**Closed as completed by lukasbestle** 2022-06-27 19:56 UTC
Labels: needs: replication 🔬

**Comment by stalburg** [comment] 2022-06-28 11:00
Thanks for the heads-up @lukasbestle!

**Comment by foobartel** [comment] 2022-06-28 11:01
Thanks for the heads-up @lukasbestle!

**Comment by Moucky** [comment] 2022-06-30 04:17
Thanks @lukasbestle, my specific issue was actually related to Varnish caching. I have disabled it and I can now browse to the file pages in the panel.
