### ISSUE TITLE
Table layout shows 'sanitzed' page title

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#4532] opened 2022-07-23 07:57 UTC
## Description
When using a special character like `'` in a page title, previous page section layouts show them as expected. The new table layout shows Unicode entities instead of the actual character.

**Screenshots**  
- Working with list view.
  
  <img width="468" alt="Working with list view" src="https://user-images.githubusercontent.com/29142128/180596096-af4ba62e-e264-40f3-a471-fecf14a8946d.png">

- Not working with table view
  
  <img width="445" alt="Not working with table view" src="https://user-images.githubusercontent.com/29142128/180596130-a1dd67e6-71b6-4015-bfbe-dc6892b9a8c2.png">

**Temporary workaround**

Add 
`    text: '{< page.title >}'`
to your blueprint.

## To reproduce
Create a page with a character that is supposedly sanitized like `'`, and show that page in a table section. 

## Your setup
**Kirby Version**  
3.7.1

**Comment by distantnative** [comment] 2022-07-23 08:05
Duplicate of https://github.com/getkirby/kirby/issues/4442

**Closed as completed** 2022-07-23 08:05 UTC
