### ISSUE TITLE
Error when trying to extend the `blocks` field

### ISSUE THREAD

**Issue by moevbiz** [k-next/kirby#4186] opened 2022-03-01 10:54 UTC
## Description
It seems to be currently not possible to extend the `blocks` (or `layout`) fields like the docs suggest:
https://getkirby.com/docs/reference/plugins/extensions/fields#extending-existing-fields__extending-the-backend
when doing this:

```php
Kirby::plugin('my/plugin', [
    'fields' => [
        'extendedblocks' => [
            'extends' => 'blocks',
        ]
],
```
it results in the following error message in the panel:

```
Component definition Kirby\Form\Field\BlocksField does not exist in file: [...]/public/kirby/src/Toolkit/Component.php line: 231
```

## To reproduce

1. Create plugin like above
2. add an "extendedblocks" field to blueprint
3. go to page
4. see error message

## Your setup
**Kirby Version**  
3.6.2

## additional info:

@afbora said: "It seems that the component class does not support this loading/registering because blocks and layout field are loaded differently from other fields (registering as a class, not as an array). An issue on GitHub would be nice."
https://discord.com/channels/525634039965679616/525641819854471168/948168719916474398

**Comment by distantnative** [comment] 2022-03-28 13:42
Duplicate of #3961

**Closed as completed by distantnative** 2022-03-28 13:42 UTC
