### ISSUE TITLE
[3.8.0-rc.2] Blueprint option with translated labels not working

### ISSUE THREAD

**Issue by doup** [k-next/kirby#4726] opened 2022-09-29 17:52 UTC
## Description

Blueprint field `select` with translated label options is not working anymore. This was working in `3.7.0`.

**Expected behavior**  

It should show the label.

**Screenshots**  

<img width="300" alt="image" src="https://user-images.githubusercontent.com/188612/193105534-e1dc58cd-a8e4-4ccc-bc35-f6ca67cd7619.png">

![image](https://user-images.githubusercontent.com/188612/193105689-1813b39f-9f15-45f6-8a5f-84ebff497bae.png)

## To reproduce

I'm using the following blueprint config:

```
    fields:
      type:
        type: select
        translate: false
        label:
          eu: Ekitaldi mota
          es: Tipo de evento
        width: 1/3
        default: single
        required: true
        options:
          single:
            eu: Egun bakarrekoa
            es: Día único
          multiple:
            eu: Egun anitzekoa
            es: Multiples dias
```

## Your setup

**Kirby Version**: `3.8.0-rc.2`

**Comment by distantnative** [comment] 2022-09-29 19:50
@doup Could you try the following and let me know if this solves your problem?

- Open `kirby/src/Blueprint/NodeI18n.php`
- Replace the `render()` method with this new code

```php
public function render(ModelWithContent $model): string|null
{
	if ($text = I18n::translate($this->translations)) {
		return $text;
	}

	if (isset($this->translations['*']) === true) {
		return I18n::translate($this->translations['*'], $this->translations['*']);
	}

	return $this->translations['en'] ?? null;
}
```

**Comment by doup** [comment] 2022-09-29 20:15
@distantnative nope, that doesn't do the trick.

**Comment by doup** [comment] 2022-09-29 20:23
Just in case I've tried changing my panel user language from `English` to `Español` (Spanish), but that didn't change anything. Also, I've double checked in `3.7.0` and it was indeed working:

![image](https://user-images.githubusercontent.com/188612/193134127-52a24263-8c3a-4e6a-8b5a-d121dc90fb64.png)

![image](https://user-images.githubusercontent.com/188612/193134261-c55ca0f2-9627-4cc4-bd0f-4ba5bc1a2ce0.png)

**Comment by distantnative** [comment] 2022-09-29 20:30
Ok what I can still reproduce is that there is no fallback when your current language is not any of the languages specified in the blueprint and there is no English one present either.

But if the current language is actually one of the ones specified in the blueprint, it works for me.

Are you sure your user language (Your Account) is set to either `eu` or `es`? The label translations are based on the Panel user language, not the currently selected content translation language.

**Comment by distantnative** [comment] 2022-09-29 20:33
Another try for the "missing EN, instead fall back to first defined language" bug:
```php
public function render(ModelWithContent $model): string|null
{
	if ($text = I18n::translate($this->translations)) {
		return $text;
	}

	if (isset($this->translations['*']) === true) {
		$key = $this->translations['*'];
		return I18n::translate($key, $key);
	}

	if (isset($this->translations['en']) === true) {
		return $this->translations['en'];
	}

	return array_values($this->translations)[0] ?? null;
}
```

**Comment by afbora** [comment] 2022-09-29 20:38
@distantnative In 3.7.5 works sample blueprint and shows first translation as fallback. But in 3.8 doesn't work. 

> Another try for the "missing EN, instead fall back to first defined language" bug:

This worked for me.

**Comment by distantnative** [comment] 2022-09-29 20:39
With https://github.com/getkirby/kirby/pull/4728 I would think that it restores same functionality as 3.7.5 for fallbacks.

**Comment by doup** [comment] 2022-09-30 07:40
**The latest snippet works for me**. I know the Panel language is based on the user language and not the content one. In my case I've the panel user in English… because I just prefer it; but my client will probably use either Spanish or Basque.

Kirby can't assume that the user language will match with the label translations (otherwise it should constraint the user language selection to the ones used in blueprint labels).

**Comment by distantnative** [comment] 2022-09-30 08:22
No exactly it shouldn't be restricted. But then you were really affected by the last edge case where the user language was not specified. That'll be fixed.

**Comment by bastianallgeier** [comment] 2022-10-02 10:40
Can we close this after the PR has been merged?

**Comment by distantnative** [comment] 2022-10-02 12:07
I would think so, yes.

**Closed as completed** 2022-10-02 12:07 UTC
