### ISSUE TITLE
Programatically storing boolean and `null` values fails

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#5961] opened 2023-11-15 09:33 UTC
## Description
As [first reported on Discord](https://discord.com/channels/525634039965679616/1173945719728648223), we are trying to programatically create and update pages with boolean or `null` values inside their content – these pages hold plugin docs with method references and thus it matters to have the right values. For some reasons, Kirby converts `null` to an empty string and `true` to `1`. Now we are aware that older version of YAML used to convert booleans to integers but the Symfony YAML handler available in newer Kirby version [is able to handle those values correctly](https://symfony.com/doc/current/reference/formats/yaml.html#booleans).

We have verified that the given YAML parser is handling content just fine by processing it directly with `Yaml::encode()` and the results are correct.

**Expected behavior**  
Boolean and `null` values should be stored without conversion if the YAML parser is able to handle it.

## To reproduce
For us, this happened with content inside a structure field, but it actually happens with any field when Kirby prepares the values for storage when calling `Form::for` inside the `update` method of `ModelWithContent.php`. I wasn't able to track it further down because I don't fully understand the internal processes, but the content is passed down correctly to the `update` method and is first changed here: https://github.com/getkirby/kirby/blob/3.9.8/src/Cms/ModelWithContent.php#L625-L629

My guess is that at some point, Kirby is converting content to strings – like `(string) $value`– without converting boolean and `null` values to their proper YAML text representation first.

**Example Field setup:**

```yaml
fields:
  name:
    type: text
  typehint:
    type: text
  default:
    type: text
```

**Example Content:**

```php
$content = [
  'name' => 'convert',
  'typeHint' => 'boolean',
  'default' => true
]
```

**Storage:**
```php
$page->update($content);
```

**Expected result:**

```yaml
name: convert
typeHint: boolean
default: true
```

**Current resul:**

```yaml
name: convert
typeHint: boolean
default: 1
```

## Your setup
**Kirby Version**  
Kirby 4 RC 1, <del>I still need to check if Kirby 3 behaves the same (I guess so though)</del> <ins>Kirby 3 with Symphony YAML handler enabled</ins>

**Comment by nilshoerrmann** [comment] 2023-11-15 09:43
It seems to be happening here: https://github.com/getkirby/kirby/blob/3.9.8/config/fields/text.php#L63

**Comment by nilshoerrmann** [comment] 2023-11-15 09:47
If I add the following condition to the converter, everything is stored as it should:

```php
if (is_bool($value)) {
    return $value === true ? 'true' : 'false';
} elseif (is_null($value)) {
    return 'null';
}
```

**Comment by nilshoerrmann** [comment] 2023-11-15 09:50
Important note: The above code only works with the Symfony handler which supports YAML 1.2. The Spyc handler is only able to handle YAML 1.0 which does not know about boolean and `null` types AFAIK.

**Comment by nilshoerrmann** [comment] 2023-11-15 09:55
So this affects Kirby 3 and 4 with Symfony YAML enabled.

**Comment by nilshoerrmann** [comment] 2023-11-15 10:09
Maybe this could be solved by an additional converter that can be set on a per field base, e. g.:

```php
return [
	'lower' => function ($value) {
		return Str::lower($value);
	},
	'slug' => function ($value) {
		return Str::slug($value);
	},
	'ucfirst' => function ($value) {
		return Str::ucfirst($value);
	},
	'upper' => function ($value) {
		return Str::upper($value);
	},
	'booleannull' => function($value) {
		if (is_bool($value)) {
			return $value === true ? 'true' : 'false';
		} elseif (is_null($value)) {
			return 'null';
		}

                return $value;
	}
];
```

This would fix this issue in a backwards compatible way.

**Comment by lukasbestle** [comment] 2023-11-15 11:44
Ah, now I understand what's going on.

In the `$page->update()` method, no YAML encoding is done. Fields are at the moment always expected to be strings. That's indeed why any passed value is casted to a string, not to YAML.

It's the same thing with structure fields. Their data is stored as YAML, but each individual field is a string.

So at the moment you need to pass `'true'` instead of `true`.

We could still discuss if it makes sense to automatically convert booleans and `null` to more useful string values, but it would be a breaking change.

**Comment by lukasbestle** [comment] 2023-11-15 11:47
Could you check if it works if you use a toggle field in the blueprint?

**Comment by nilshoerrmann** [comment] 2023-11-15 12:09
> Could you check if it works if you use a toggle field in the blueprint?

I've not tested it, but the field features this code, so I guess yes:

```
return $this->value() === true ? 'true' : 'false';
```

> Ah, now I understand what's going on.

Same here. I think this would have been less irritating if we weren't storing content to a structure field which gives you plain YAML in the content file. It completely obfuscated to me why those content types got lost.

I think Kirby's logic here is not wrong though, especially with the old YAML parser in mind. But the current solution is not ideal either. The cleanest and simplest solutions would be to have some kind of YAML field type or converter:

- **field:** same as the text field but actually parsing and storing the content as YAML. Could either be a YAML input or a YAML structure. In general, this sounds like a good candidate for a plugin.
- **converter:** this could be something simple as I suggested above or a converter the actually parses the field as YAML. As converters are optional, this wouldn't have any compatibility impact.

> We could still discuss if it makes sense to automatically convert booleans and null to more useful string values, but it would be a breaking change.

Given how Kirby helps with content in other areas it would make sense to me to have a simple helper as part of the core (think converter). It would be great to have some information in the docs in the context of text and structure fields and especially virtual pages.

**Comment by lukasbestle** [comment] 2023-11-15 20:16
The issue is that each form is really just a set of key strings and value strings. The value strings become part of the content file, structure YAML or blocks/layout JSON. An individual field cannot return YAML per se as the outer layer needs a string (returning YAML wouldn't make the YAML structure be nested as you would expect, it would just be a YAML string inside a YAML/JSON/KirbyData structure). So TBH I feel like the solutions you suggest are not really generally applicable.

I've just tested the toggle field. It indeed handles the string conversion from a boolean as I would expect. This is IMO the best solution as it also expresses the expected content format and validation rules.

The second-best solution would be to manually cast values to string. Passing strings as field values is always the safest way that cannot go wrong.

I'm closing this as I wouldn't consider this a bug. Feel free to add a feedback entry on Nolt, we might reconsider it later.

**Closed as not planned by lukasbestle** 2023-11-15 20:16 UTC

**Comment by nilshoerrmann** [comment] 2023-11-15 20:26
I'm fine with this :+1: But I think you should adapt the structure field docs because they are misleading. 
[From the introduction](https://getkirby.com/docs/reference/panel/fields/structure):

> The structure field makes it possible to add multiple complex entries to a field, which will be stored as [YAML](https://getkirby.com/docs/glossary/#yaml). A typical use case would be a list of addresses, team members or a restaurant menu.

Yes, it does store YAML. No, it doesn't store YAML – see this issue ;)
It's a very Kirby-specific mixture of YAML structure with field values which will not be clear to new users (it wasn't even to me who should have known better after using Kirby for quite a while now).

**Comment by lukasbestle** [comment] 2023-11-15 21:09
Good point, I've updated the structure field docs – and object field docs while I was at it. :)

**Comment by nilshoerrmann** [comment] 2023-11-16 07:09
Thank you!
