### ISSUE TITLE
Table Layout: Ampersand is not rendered in column entries

### ISSUE THREAD

**Issue by trych** [k-next/kirby#4534] opened 2022-07-26 13:53 UTC
## Description
Ampersands (and possibly other characters) are not rendered correctly in the default Type column of a page section in table layout as well as in columns without a type set (setting it to text makes it render correctly).  

**Expected behavior**  
Characters should render correctly.

**Screenshots**  
![20220726-155214_Screenshot_morgen test](https://user-images.githubusercontent.com/9803905/181022830-796693de-fac7-4090-b4e4-ede1ca4c7bc7.png)

## Your setup
**Kirby Version**  
3.7.1

**Comment by lukasbestle** [comment] 2022-07-26 13:57
Duplicate of #4442.

**Closed as completed** 2022-07-26 13:57 UTC
