### ISSUE TITLE
Site in Panel is untranslatable

### ISSUE THREAD

**Issue by herrajon** [k-next/kirby#3936] opened 2021-11-16 11:50 UTC
The Site option in the Panel in the Topbar is not translatable. Tried with the translation key: **"site"** and **"view.site"** in /kirby/i18n/translations/is_IS.json.

**To Reproduce**  
1. Go to your Kirby site of choice
2. Enter the Panel
3. Look at the Topbar option: It displays Site
4. Switch your profile language to Deutsch
5. Look at the Topbar option: It still displays Site
6. Switch your profile language to Türkçe
7. Look at the Topbar option: It still displays Site
8. Switch your profile language to Íslenska
9. Be confused 
10. Look at the Topbar option: It still display Site

**Expected behaviour**  
It should be possible to translate Site to a word in the language of question.

- For German: Perhaps Seite
- For Turkish: Perhaps Sitesi
- For Icelandic: Definetly vefsvæði

Another option would be to display the name of the website i.e. 'Ingrids Furniture Store', 'Red Meat Best Recipes', 'Eleven things to do when chased by a White Bear' or 'getkirby.com'

**Screenshots**  
![image](https://user-images.githubusercontent.com/182769/141979648-4e8b98fe-4e41-4a14-9f6f-b0d428c624ba.png)

**Kirby Version**  
Tested in Kirby CMS v. 3.6 RC-5

Thanks
-j

**Comment by afbora** [comment] 2021-11-16 12:10
@herrajon Actually you can already change from `site.yml` 🙂 

````yml
# /site/blueprints/site.yml

title:
  en: Your site
  tr: Websiteniz
````

**Comment by nilshoerrmann** [comment] 2021-11-16 12:14
> For German: Perhaps Seite

`Seite` is very unspecific (everything is a page in Kirby). From an editor point of view `Übersicht` or `Startseite` would make sense as a default in German in my eyes. While `Site` is a common term for web developers in Germany as well, I don't think is self-explanatory to editors and "normal" users.

> Actually you can already change from site.yml 🙂

<del>I've got `Title: Kirby Plugins` defined in my site blueprint on a test install and it only prints that title in the breadcrumb navigation not the menu. Or does that only work with the multilingual notation?</del>
<ins>Scratch that: I confused the blueprint setting and the value in the content file … Sorry!</ins>

**Comment by nilshoerrmann** [comment] 2021-11-16 12:21
Looking at this, it's a bit confusing that the breadcrumbs take the value from the content file while the main navigation takes the value from the site blueprint. Icon and link are the same – it looks like two different approaches to the same thing …

**Comment by herrajon** [comment] 2021-11-16 12:33
@afbora @nilshoerrmann site.yml. That is a nice one. Why did I not think of that? But I am a firm believer in that "The Defaults Should be Best". Especially for new users this would be an issue although a very minor one. 

Which word it would be replaced with should be a matter of translation. What the Site means in Kirby is "The Place where you add your stuff".

I agree with you @nilshoerrmann that with the breadcrumbs it is a little bit confusing that the breadcrumbs take their first value from the Sitename i.e. 'getkirby.com' or 'The Wedding Store' but it makes sense in the long run as the Sitename is a 'child' to the 'Site' category/option.

**Comment by distantnative** [comment] 2021-11-25 13:49
@bastianallgeier what would be the solution here?

- Using the site's name for the dropdown menu: I would find that confusing too. The whole Panel is about e.g. `The Wedding Store` not just that menu entry.
- Using `Site`for the breadcrumb as well: Could be an option, although seeing the site name there I do like.
- Rename the `Site` entry to `Content`: in the menu, this would probably be the more fitting name what's behind that menu entry. But then we have bigger disconnect to understand that one needs to adapt `site.yml` to configure the first view behind `Content`

**Comment by herrajon** [comment] 2021-11-25 14:10
I think Herr Hoffmann is spot on.

If I may add my six cents to the discussion.

The dropdown menu is various aspects/facets (ooo as in sides of a diamond) of the application/system/kirby.

So it is most logical NOT to „localise” that in regard to the site name or brand.  This is where the „stuff” (read content) the user is putting on line so it would be clear and simple and brilliant to call it content. That would describe the function of that aspect/facet of the application. Also it would be very straightforward to translate that as most nations/languages have content in some form.

The best way for the breadcrumbs in my opinion is to use the sitename as it is currently. It is after all part or sub of the „content” aspect. 

-j

**Comment by distantnative** [comment] 2021-11-30 14:12
We discussed this internally in more detail. Summarising our thoughts:

- It's not a regression. Setting the title in `site.yml` blueprint works as it did in 3.5.
- The menu label is controlled by the `site.yml` title and falls back to the `view.site` translation string. This means that you can control and translate the menu label for every installation very easily.
- We are updating our kits to not set the title in the site blueprint, so that the `view.site` translation strings are actually used by default ink our kits.
- The breadcrumb solution is correct in our opinion and it's a solution that was based on user feedback years ago.

We will therefore close this issue. If there is demand to actually change this feature/behaviour, please open a feedback on Nolt (https://feedback.getkirby.com/) to evaluate how much that idea resonates within the community.

Thanks for the good discussion on this! We think that's the most productive way to move forward.

**Closed as completed by distantnative** 2021-11-30 14:12 UTC

**Comment by herrajon** [comment] 2021-11-30 14:22
Onwards.
