### ISSUE TITLE
[v4] Randomly unauthenticated error

### ISSUE THREAD

**Issue by luglio7** [k-next/kirby#5408] opened 2023-07-24 16:20 UTC
## Description
Kirby 4 alpha 5 randomly generates unathenticated errors, tried with another fresh install and the error persist.

**Screenshots**  
Here's a video url: https://drive.google.com/file/d/16Sp0c42MxsD3_qHQPivmA2WV2FHifpBc/view?usp=sharing 

## To reproduce
I really don't know, it's a clean setup with some blueprints edits.

**Comment by afbora** [comment] 2023-07-24 18:16
I tried a lot but cannot reproduce the issue. May be need more information about your enviorement.

**Comment by afbora** [comment] 2023-07-28 11:46
Closing for now. Feel free post new replicate info when you find more clues 👍

**Closed as not planned by afbora** 2023-07-28 11:46 UTC
Labels: needs: information ❓, needs: replication 🔬

**Comment by bnomei** [comment] 2023-12-06 14:16
osx 14.1.2, laravel herd, php8.2
did not verify in live production server.

i have a tab with sections of pages and if i keep clicking the tab head "articles" or if i navigate to the page it hapend seemingly at random
![CleanShot 2023-12-06 at 14 08 42 2](https://github.com/getkirby/kirby/assets/3265642/04ebaf4c-6228-481f-bf31-c907da6d0964)

that the sections fail to load
![CleanShot 2023-12-06 at 14 09 05 2](https://github.com/getkirby/kirby/assets/3265642/7d8c5c23-4422-4c56-a15f-2e6d44dc74c1)

the responses for repeated clicking of the tab "articles" look like this
![CleanShot 2023-12-06 at 13 47 40](https://github.com/getkirby/kirby/assets/3265642/e439852b-8362-41a5-9851-92c4b08a9cd8)

1. the current panel view get redirected to something like http://XXX.test/api/site/sections/articles_drafts?page=1
```json
{"status":"error","message":"Unauthenticated","code":401,"exception":"Kirby\\Exception\\AuthException","key":"error.auth","file":"..\/kirby\/config\/api\/authentication.php","line":15,"details":[],"route":"site\/sections\/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)"}
```

2. or rarely a 30 sec php timeout even though only 2 seconds have passed.
3. or a could not write to file (could not trace which file since tracing all f::writes until i could reproduce was too much for ray.app)

**Comment by distantnative** [comment] 2023-12-06 14:48
@bnomei Could you please post this as a new issue. It's hard to keep track of closed issues and I think mixing up topics a bit. Thank you 🙏

**Comment by bnomei** [comment] 2023-12-06 15:00
the sections themself are simple and each extending this one only changing the status

**base**
```yml
headline: Articles
type: pages
layout: list
image: false
parent: site.find('articles')
```

**one section**
```yml
      articles_drafts:
        label: Drafts (hidden)
        extends: sections/articles
        status: drafts
```

changing the section type from pages to files or info does not prevent the issue from appearing. nor does removing all other tabs and fields from the site blueprint fix it.

an totally empty site blueprint (yielding the info section in the panel) does successfully avoid the issue.

a single to level `fields:` definition seems to avoid the issue as well.

a long time later digging code...
i think i found it. classical dev error. seems like i had a site()->index() call deep down in my code on the route:after hook with `$final === true` and that applied to the multiple requests in the panel. like 5 for refreshing that one view. thus the heavy load and the php fpm stopping processes and causing errors.

**Comment by bnomei** [comment] 2023-12-06 15:03
> @bnomei Could you please post this as a new issue. It's hard to keep track of closed issues and I think mixing up topics a bit. Thank you 🙏

decided to post final findings here since the issue is resolved for me now.
