### ISSUE TITLE
Session timeout throws Uncaught TypeError

### ISSUE THREAD

**Issue by GiantCrocodile** [k-next/kirby#4373] opened 2022-06-14 20:52 UTC
## Description
When the timeout in the admin panel triggers, an error is thrown in the console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'querySelector')
    at s.focus (index.js:1:214529)
    at index.js:1:215115
```

**Expected behavior**  
No error thrown.

**Screenshots**  
![grafik](https://user-images.githubusercontent.com/6271057/173686266-0f02c64a-e04a-4b48-aa5e-f3a8bc93cf15.png)

## To reproduce

1. Go to admin panel and log in (checkbox for long session not ticket)
2. switch the tab for timeout to work
3. check console after you have been logged out/session has been cancelled

## Your setup
happened with latest v3.6 release as well as with 3.7.0 rc1

**Console output**  

```
Uncaught TypeError: Cannot read properties of undefined (reading 'querySelector')
    at s.focus (index.js:1:214529)
    at index.js:1:215115
```

**Your system (please complete the following information)**
Windows 11 with WAMP setup

**Comment by afbora** [comment] 2022-06-14 21:50
I can reproduce the issue. I think optional chaining will fix the issue.

### Related issue lines
- https://github.com/getkirby/kirby/blob/3.7.0-rc.1/panel/src/components/Layout/Overlay.vue#L62
- https://github.com/getkirby/kirby/blob/3.7.0-rc.1/panel/src/components/Layout/Overlay.vue#L106

**Comment by distantnative** [comment] 2022-09-17 14:17
Somehow I am too stupid to get a timeout... 😅

**Comment by lukasbestle** [comment] 2022-09-17 14:47
This should do the trick to force a pretty immediate session timeout:

```php
return [
    'session' => [
        'durationNormal' => 1,
        'durationLong'   => 1,
        'timeout'        => 1,
    ]
];
```

**Comment by distantnative** [comment] 2022-09-17 15:04
That's what I have, but no matter how long I stay away form the Panel, once I return and click around everything just works fine, no timeout.

**Comment by lukasbestle** [comment] 2022-09-17 19:11
Have you logged out and logged back in? The options only apply to new sessions.

**Comment by afbora** [comment] 2022-09-20 10:06
I can reproduce the issue with following steps and options on 3.7.0.  But not for `develop` branch. I think, we can close the issue.

**Issue steps for 3.7.0**

1. Set session options with below codes
2. Go to panel login page
3. Open console (keep open)
4. Delete all storage and cookies from `application` tab
5. Login panel
6. Go go any page
7. Edit any input without save
8. Switch the tab
9. Wait ~15-20 seconds
10. See error log in browser console



````php
<?php

return [
    'debug' => true,
    'session' => [
        'durationNormal' => 15,
        'timeout'        => 5,
    ]
];
````

**Comment by distantnative** [comment] 2022-09-20 10:15
Ahh, I was only trying with develop. But maybe then it got fixed already.

**Comment by afbora** [comment] 2022-09-20 10:23
Then I'm closing the issue because it seems to be fixed already. Of course, it will reopen if reoccurs the problem.

**Closed as completed by afbora** 2022-09-20 10:23 UTC
