### ISSUE TITLE
[3.6.0-beta.2] Strange behavior with pasting HTML to blocks

### ISSUE THREAD

**Issue by MaluNoPeleke** [k-next/kirby#3735] opened 2021-09-30 15:03 UTC
**Describe the bug**  
I have discovered several strange behaviors when I tried to copy & paste content from HTML into blocks.

**To Reproduce bug 1**  
1. Go to https://loremipsum.de/
2. Copy the second block including the headline "Warum Lorem Ipsum?"
3. Paste it as a block
4. The headline is missing

**Expected behavior**  
Headline is included

**To Reproduce bug 2**  
1. Go to https://jsfiddle.net/m0681dr2/
2. Copy the content of the output window
3. Paste it as a block
4. Line break for the last sentence is missing
5. Copy only the paragraph part without the headline
6. Line break shows up

**Expected behavior**  
Line break shows up always

**Screenshots**  

**Kirby Version**  
Kirby 3.6.0-beta.2

**Console output**  
None

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Chrome
 - Version: 94 

**Additional context**

**Comment by afbora** [comment] 2021-09-30 15:18
I cannot reproduce the first issue, but I can see the second.

**Comment by MaluNoPeleke** [comment] 2021-09-30 15:25
I mean this block:
![image](https://user-images.githubusercontent.com/1446541/135484660-4bb5c0df-2039-4597-9011-2d3b08f6c900.png)
It never pastes the headline afterwards.

btw: have you seen my email regarding another strange issue @afbora ?

**Comment by afbora** [comment] 2021-09-30 15:32
Make sure `headings` block allowed.

![paste-2](https://user-images.githubusercontent.com/3393422/135485722-57847121-a30e-435e-96d4-795eab025405.gif)

**Comment by afbora** [comment] 2021-09-30 15:34
@MaluNoPeleke Your email has been marked as spam, I just got it. I'll reply after check.

**Comment by afbora** [comment] 2021-09-30 18:00
@bastianallgeier The break line works when we add a new mark to parsley but is this a correct solution?

https://github.com/getkirby/kirby/blob/develop/src/Parsley/Schema/Blocks.php#L72

**Comment by MaluNoPeleke** [comment] 2021-09-30 18:04
> Make sure `headings` block allowed.
> 
> ![paste-2](https://user-images.githubusercontent.com/3393422/135485722-57847121-a30e-435e-96d4-795eab025405.gif)

Headings block is allowed

**Comment by afbora** [comment] 2021-09-30 18:07
Can you share blueprint of blocks field?

**Comment by MaluNoPeleke** [comment] 2021-09-30 18:28
I just tested it again on a Windows laptop and there it works as well.

**Comment by afbora** [comment] 2021-09-30 18:31
So It's an issue that only occurs on Mac then.

**Comment by bastianallgeier** [comment] 2021-10-05 11:07
@afbora you were heading in the right direction. I added br as a mark, but I also had to change the render logic for inline elements. 

My PR should fix both issues. Please give it a try.

**Comment by bastianallgeier** [comment] 2021-10-05 11:26
✅

**Closed as completed by bastianallgeier** 2021-10-05 11:26 UTC
