### ISSUE TITLE
[v4] Link fields lose their type in structure field editor

### ISSUE THREAD

**Issue by alexdeloy** [k-next/kirby#5815] opened 2023-10-18 16:40 UTC
## Description
Link fields inside a structure can be edited as expected and show their expected value inside the tabular preview.
When going back and forth with the arrows in the details of the structure field, the type of the link field does not change automatically and remains on the one that was initially opened. When trying to save, a (browser) validation error can be shown, depending on the contents (e.g. this is not a valid E-mail address)

**Expected behavior**  
Link fields inside a structure field should show the correct type when navigating via the arrow buttons of the structure.

![grafik](https://github.com/getkirby/kirby/assets/1140300/8f725930-1a03-415a-9997-db699289c788)

## To reproduce
1. Create a structure field and add a link field somewhere
2. Add some content (including links with different types) to that structure and save
3. Open the structure and click on any entry
4. Navigate with the arrow buttons of the structure field

## Your setup
**Kirby Version** v4.0.0-beta2
**Console output**  -

 - Device: PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 118.0.2

**Comment by lukasbestle** [comment] 2023-10-18 20:18
Looks like a duplicate of #5814, will be fixed in beta 3.

**Closed as completed by lukasbestle** 2023-10-18 20:18 UTC
