### ISSUE TITLE
Content locking .lock files and sorting pages crash git sync

### ISSUE THREAD

**Issue by fabianmichael** [k-next/kirby#5108] opened 2023-03-16 10:16 UTC
## Description
I use git for deploying most of my projects, which usually works without any major issues. Problems arise, when .lock-files remain in the content folder while the site is being updated.

**Expected behavior**  
`.lock` files used for content locking should not interfere with updating via git. A better separation of content files and temporary files would be preferred to avoid this. Caching, thumbnails and sessions all have their own custom folders, that can easily be cleared and even moved to a different location.

## To reproduce

1. Setup an average Kirby project, that is synchronized with a central repo using git with the default `.gitignore` setup as provided by Kirby’s starterkit/plainkit.
2. Create 2 pages and publish them. Pages at top-level should use numeric sorting (default behavior). Your content folder should now contain two folders with a sorting number prefix, e.g. `1_foo` and `2_bar`. Commit and sync with git repo.
3. Create a second instance of the setup, re-order pages and commit back to the repo. Your content folder should now contain the folders `1_bar` and `2_foo`
4. Log into the panel of your first instance (without pulling from git) and start editing the `foo`-page, so a `.lock`-files is created within its folder.
5. Now run `git pull` on your first instance. **Result:** the content folder will now contain three folders: `1_bar` and `2_foo` (the real pages with the correct content) and and almost empty folder `1_foo`, which only contains `.lock`. If the folder was empty, git would delete it. But since there’s the lock-file, it will stay in place. Now the page `foo` is present twice under the same id, which will mess up the installation. The duplicated page often becomes inaccessible and Kirby will even attempt to generate a new UUID for this empty page. This usually crashes the whole site.

## Your setup

**Kirby Version**  
3.9.2

**Comment by distantnative** [comment] 2023-03-16 11:25
I won't argue against the `.lock` files not being the greatest.
But I was wondering, don't you run into very similar problems when step 4 would be changing significant parts of the content and also  changing template?

EDIT: mainly what I was wondering if that isn't a general a problem of git setups where content is edited in multiple places but existing changes aren't pulled before adding own changes. Just screams for merge conflicts I would think.

**Comment by fabianmichael** [comment] 2023-03-16 11:29
@distantnative To be honest, I generally only have very few projects where I allow editors to change templates, so I don’t have any experience with that (but I guess you’re right). Generally, I try to avoid editing content in multiple places to avoid merge conflicts.

To get around the issue described above, I mostly try to stay away from numeric sorting in Kirby and have switched to `zero` sorting for most of my projects. A blocks field with special link and submenu blocks (or whatever the menu requires) is used as menu builder then. Adds quite a bit of complexity, but saves me lots of headaches.

**Comment by lukasbestle** [comment] 2023-03-19 15:57
TBH I agree with Nico. Even if we removed the `.lock` files, there could still be merge conflicts when a page folder is moved in instance A but the page is edited in instance B. Git won't know that it's the same page, so it won't be able to merge those changes automatically. But even without moving the page folder, merge conflicts can still occur (e.g. when editing the page in instance A but deleting it entirely in instance B). Neither Kirby nor Git can automatically resolve such conflicts. So I feel like this is something we cannot fix.

**Comment by fabianmichael** [comment] 2023-03-20 08:51
@lukasbestle Technically, I fully agree with you. In practice however, 95%+ of (my clients’) merge conflicts happen because somebody attempts to re-order pages on one instance, sometimes even by accident. Usually, I take care upfront to avoid any painful merge conflicts by announcing update times for live server, disabling the panel temporarily etc. but sometimes something slips through and it only discovered after a server has aleady been updated.

Having the `.lock` files moved from the content folder to e.g. the cache folder along the UUID cache would have the added benefit, that it would allow for further consolidation of temporary files. A lot of installations I have seen over the last months use a custom folder setup with a `storage` folder for all temporary files. That would also offer an opportunity to ease the implementation of content locking for virtual files without the need for additional database tables or custom content locking classes.

**Comment by lukasbestle** [comment] 2023-03-23 20:58
As I wrote, this is not just a problem caused by lock files. Once the same page is modified in two different ways on two different servers (e.g. renamed/moved/deleted on one and edited on the other), there will be a merge conflict.

The steps to reproduce from your first post are a case where the issue only occurs because of the lock file. However it would already be enough to save the page in the first instance (changing the content file) to trigger a full merge conflict. So to be honest I don't feel like moving the lock files to a storage folder would fundamentally improve the behavior regarding merge conflicts.

About consolidation of temporary files: Lock files are not temporary files. They represent content state, so if you cleared them like a cache, you would break the state because suddenly two different users can have unsaved changes at the same time, introducing another layer of merge conflicts and Panel errors. In the future we have the goal to replace the lock files with a different implementation to be able to support features like easier collaboration, page previews and revisions. But the new implementation will still store its state in the content folder for the mentioned reason.

About virtual pages/virtual files: You are right that those classes currently need to handle locking as well if editing in the Panel is needed. This would indeed be simpler with a global store, but as explained I don't think it would be viable at this point.

I'm closing this issue for now because we won't be able to solve both needs (robust state management and separation from the content folder structure) simultaneously with the way locking works at the moment. Thanks for your input, we'll keep it in mind for future changes to the locking setup.

**Closed as not planned by lukasbestle** 2023-03-23 20:58 UTC
