### ISSUE TITLE
[v4] Tag field offers misleading create-feature ignoring the accept:options-setting / cuts off long options

### ISSUE THREAD

**Issue by twiro** [k-next/kirby#5535] opened 2023-08-31 09:06 UTC
This bug seems to be directly related to **[the same problems](#5533)** I experienced with the **multiselect field** in the latest v4-alpha-release.

## Description

1. The tag field ignores the blueprint-setting `accept: options` and always comes up with a misleading **create**-option whenever a search for a non-existing option is performed. _(This happens with both static and dynamic options / using the create-feature doesn't do anything at all.)_
2. The tag field cuts of **options with long titles** due to its limited width.

**Expected behavior**  

1. The tag field should not contain a **create**-option if the blueprint contains `accept: options`.
2. The tag field should not **cut off options** as long as there is enough space left to show them properly.

**Screenshots**

<img width="1639" alt="kirby-tag-field-bug-v4" src="https://github.com/getkirby/kirby/assets/870227/9aa4cac8-54b6-47ea-bfa0-9b3d6fd5e712">

## To reproduce

1. Take any example with options from the official **[tag-field-reference](https://getkirby.com/docs/reference/panel/fields/tags)** and try it out in the [latest alpha-release](https://github.com/getkirby/kirby/releases/tag/4.0.0-alpha.7).
2. Add the `accept: options`-setting to the blueprint.
3. Try to use the **create**-option.
4. Try out some options with really long names.

## Your setup

**Kirby Version:**   [4.0.0-alpha.7](https://github.com/getkirby/kirby/releases/tag/4.0.0-alpha.7).

**Comment by bastianallgeier** [comment] 2023-08-31 10:10
The accept option is now fixed. The cut-off problem is a duplicate of https://github.com/getkirby/kirby/issues/5533

**Closed as completed** 2023-08-31 10:09 UTC
