### ISSUE TITLE
Plugin page model doesn't apply when changing page status to "unlisted" or "public".

### ISSUE THREAD

**Issue by Dreytac** [k-next/kirby#4589] opened 2022-08-18 20:11 UTC
## Description
I have a page model assigned to a template and adding a content representation causes that representation to use the default page model and not the page model of the template.

Oddly, if the page status is `draft`, the preview works fine. Once the page is promoted to `unlisted` or `public`, the page model is no longer applied.

It is extremely similar to issue #1362.

**Expected behavior**  
When using a content representation, the page model for the template should be used regardless of page status.

## To reproduce
1. Create a content representation for an existing template with a page model (in my case `.json`).
2. Make sure the page status is set to `unlisted` or `public`.
3. Try and call a method from the page model in that content representations template. The call returns `null` as the result.
4. Set the page status to `draft`.
5. Preview the page and the page model should now apply.

## Your setup
**Kirby Version**  
v3.7.3

**Comment by lukasbestle** [comment] 2022-08-18 20:14
Do you have a template file for the main template (without content representation extension), i.e. `/site/templates/your-template.php`?

**Comment by Dreytac** [comment] 2022-08-18 20:16
Yes, here is my current plugin:

```
<?php
Kirby::plugin("hobbyhome/minecraft", [
	"blueprints" => [
		"pages/minecraft" => __DIR__ . "/blueprints/pages/minecraft.yml",
	],
	"pageModels" => [
		"minecraft" => include __DIR__ . "/models/minecraft.php",
	],
	"templates" => [
		"minecraft" => __DIR__ . "/templates/minecraft.php",
		"minecraft.json" => __DIR__ . "/templates/minecraft.json.php",
	],
]);
```

**Comment by afbora** [comment] 2022-08-18 21:21
AFAIK it seems that registering the page model is not correct. You can register like that:

````php
<?php

require __DIR__ . "/models/minecraft.php";

Kirby::plugin("hobbyhome/minecraft", [
  "pageModels" => [
    "minecraft" => 'MinecraftPage',
  ]
]);

**Comment by Dreytac** [comment] 2022-08-18 21:29
> AFAIK it seems that registering the page model is not correct. You can register like that:

That doesn't appear to fix the issue for me. As soon as I set the page status to `unlisted` or `public`, I get the same problem.

Edit: Just to confirm, having the page status set to `draft` and viewing the content representation works perfectly. The page model is loaded correctly. It's only when the page status is updated to `unlisted` or `public` that the page model fails to apply.

**Comment by Dreytac** [comment] 2022-08-20 13:34
Ok, I am really confused as to what is happening here. So I created a new plugin:
````
<?php
Kirby::plugin("hobbyhome/minecraft", [
	"blueprints" => [
		"pages/minecraft" => __DIR__ . "/blueprints/pages/minecraft.yml",
	],
	"pageModels" => [
		"minecraft" => include __DIR__ . "/models/minecraft.php",
	],
	"templates" => [
		"minecraft" => __DIR__ . "/templates/minecraft.php",
	],
]);
````
The blueprint:
````
title: Minecraft
````
The model:
````
<?php
class MinecraftPage extends Page
{
	
}

return "MinecraftPage";
````
And the template:
````
<?php dump($page); ?>
````

1. I created a new page with the Minecraft template.
2. I viewed the actual page on the website and it dumps a `MinecraftPage Object`.
3. I set the page status to `unlisted`.
4. I viewed the actual page on the website again but this time it dumps a `Kirby\Cms\Page Object`.

None of my other plugins do this and I'm at a complete loss. I'm going to assume I've done something wrong at this point.

**Comment by lukasbestle** [comment] 2022-08-20 13:42
@Dreytac Have you tried putting the blueprint, template and model in the `site` folder without using a plugin? It shouldn't make a difference, but maybe that's where the bug comes from.

**Comment by Dreytac** [comment] 2022-08-20 13:59
I've narrowed it down to the use of a ~~`findBy()`~~ `index()` call in the routes of another of my plugins...

Removing everything to just the broken code, in my other plugin I have:
````
"routes" => function ($kirby) {
    $routes = [];

    if ($galleryPage = site()->index()->findBy("intendedTemplate", "gallery")) {

    }

    return $routes;
},
````
If I comment out that if statement, the model is applied correctly.

What's more odd is if I copy that exact code and put it in the Minecraft plugin instead, everything works... It's strange that it's only the page model that is affected by the ~~`findBy()`~~ `index()` call. The page still gets the correct template.

@lukasbestle Moving them to the `site` folder doesn't change the result.

Edit: It appears to be the `index()` call that breaks.

**Comment by Dreytac** [comment] 2022-08-20 14:37
I've narrowed it even further to calling `site()->children()` in the route function. A `draft` isn't broken by this call.

Calling `site()->childrenAndDrafts()` WILL break a draft as well.

That's about as far as I can get with my knowledge.

**Comment by lukasbestle** [comment] 2022-08-20 15:08
Thanks for the additional information. Closing this issue as duplicate of https://github.com/getkirby/kirby/issues/4591.

**Closed as completed by lukasbestle** 2022-08-20 15:08 UTC
