### ISSUE TITLE
update SimpleImage lib

### ISSUE THREAD

**Issue by bnomei** [k-next/kirby#5089] opened 2023-03-03 16:27 UTC
## Description

SimpleImage lib was recently updated to 4.0 closing issues with avif support and upgrading color extractor lib. the breaking change is dropping php 5.6 and 7.4 support. 

further more additional options can be forwarded to the SimpleImage API for better control about generated files - like avif speed or png compression. SimpleImage had used defaults before for these values. maybe values from kirbys thumb options can be forwarded up to that method?

https://github.com/claviska/SimpleImage#options-array

https://github.com/claviska/SimpleImage/releases/tag/4.0.0

**Comment by lukasbestle** [comment] 2023-03-04 20:07
Thanks for letting us know. 👍

**Comment by distantnative** [comment] 2023-03-16 22:20
We might have to wait for one bug to be fixed in 4.0.0: https://github.com/claviska/SimpleImage/issues/317

**Comment by distantnative** [comment] 2023-03-19 14:52
@lukasbestle would you say it's viable to monkey-patch this on our side while the fix for the official repo is waiting?

**Comment by lukasbestle** [comment] 2023-03-19 15:17
@distantnative Your proposed solution in https://github.com/claviska/SimpleImage/issues/317 looks correct to me. The issue is just that fixing it in the `vendor` folder will only work for users who don't install Kirby with Composer (as Composer will ignore our patch).

**Comment by distantnative** [comment] 2023-03-19 17:40
Ok, then we probably have to wait

**Comment by bnomei** [comment] 2023-03-19 18:00
since i PRed most of v4 i will add a fix for that soon and ping the core maintainer

**Comment by distantnative** [comment] 2023-03-19 18:06
Great @bnomei, won't probably in the RC for 3.9.3 then, but hopefully before the actual release 🤞

**Comment by bnomei** [comment] 2023-03-20 15:32
[v4.0.1](https://github.com/claviska/SimpleImage/releases/tag/4.0.1) tagged just now

**Comment by distantnative** [comment] 2023-03-20 17:44
@bnomei but it does seem to miss the fix

**Comment by distantnative** [comment] 2023-03-20 18:34
@bnomei now it is https://github.com/getkirby/kirby/pull/5121

**Comment by bnomei** [comment] 2023-03-20 22:44
did you have the chance to take a look at the options array introduced in v4?
i was hopeping we could utilize these with the kirby thumb options. 

that would make it possible to convert to different formats like jpg-to-avif or set png compression levels when creating a thumb.

**Comment by distantnative** [comment] 2023-03-20 23:02
@bnomei have you looked at the PR? I would think that's what it does now with passing the full $options array or am I understanding it wrong?

**Comment by bnomei** [comment] 2023-03-21 08:51
sorry. no i did not. but will do now. 

i read the PR description but did not see anything mentioned there - thats why i asked.

**Comment by bastianallgeier** [comment] 2023-03-23 09:14
✅

**Closed as completed** 2023-03-23 09:14 UTC
