### ISSUE TITLE
[v4] Layout field throws error on trying to add text block

### ISSUE THREAD

**Issue by nilsmielke** [k-next/kirby#5765] opened 2023-10-09 12:42 UTC
## Description
I have a layout field defined with a limited set of blocks (heading, text, list, image). When adding an image, there is no problem. As soon, as I try to add a text, list or heading block, though, the field starts throwing errors. For a text block the message is “this.content.text is null” on every action, that follows trying to add the block.
Reloading the panel page, the field looks okay again. As soon as I try to edit … error. 
If I reset the field completely (read: delete all layout content) and I only add image blocks, everything works as expected.
Adding one of the other field types … error.

## To reproduce
No idea, what triggers this.
I reverted the site to a backuped 3.9.6.1 version. There the problem did not exist.
I cannot reproduce it in a Starterkit running 4.0.0-beta.2, either.

## Your setup
**Kirby Version**  
4.0.0-beta.2

**Console output**  
![Bildschirmfoto 2023-10-09 um 14 33 54](https://github.com/getkirby/kirby/assets/8496033/da56cd47-4a6b-44e4-b8a9-c4d41947a9c8)

**Your system (please complete the following information)**
 - Device: MacBook Pro 14" 2021
 - OS: macOS 13.5.2
 - Browser: Firefox
 - Version: 118.0.1 (latest)

**Comment by afbora** [comment] 2023-10-09 13:36
You couldn't reproduce the issue in 4.0.0-beta.2 starterkit, so do you have any plugins or custom js?

**Comment by nilsmielke** [comment] 2023-10-09 21:31
You are right, of course, @afbora.
Should have thought of a plugin potentially being the problem.
Sorry for wasting your time.

**Comment by lukasbestle** [comment] 2023-10-10 05:14
I'm closing this for now. If you are able to track down what causes the issue and it turns out to be a bug in Kirby, please let us know and we'll reopen.

**Closed as not planned** 2023-10-10 05:14 UTC
Labels: needs: replication 🔬

**Comment by nilsmielke** [comment] 2023-10-10 07:30
The “Extended Writer” plugin was responsible for those errors.
As I realised—after Ahmet’s nudge—the plugin has been sunset. With the upcoming release of Kirby v4 its features have found their way into `core`.
