### ISSUE TITLE
[Panel] Long page title pushes the prev/next page navigation out of view

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#6520] opened 2024-07-02 09:25 UTC
## Description
I was just navigating through some pages using the prev/next buttons and had to stop here because suddenly the buttons where gone:

![CleanShot 2024-07-02 at 11 12 31](https://github.com/getkirby/kirby/assets/60777/bc2027f4-1ccd-44a6-af09-b14638838013)

## Your setup
**Kirby Version**  
4.3.0

Found in Firefox 127
Confirmed in Chrome 126

**Comment by afbora** [comment] 2024-07-02 10:29
Duplicate of #6348

**Closed as not planned by afbora** 2024-07-02 10:29 UTC

**Comment by mrflix** [comment] 2024-07-02 11:08
Thanks @afbora. I checked existing tickets but must have overlooked it.

**Comment by afbora** [comment] 2024-07-02 11:09
No problem. Sometimes I can overlooked too 🙈
