### ISSUE TITLE
Lock requests fail with 403 Forbidden after session timeout

### ISSUE THREAD

**Issue by GiantCrocodile** [k-next/kirby#5141] opened 2023-04-08 19:49 UTC
## Description
When you are inactive in the panel, you get auto logged out and lock requests fail with 403 Forbidden HTTP errors.

**Expected behavior**  
No unnecessary lock requests are made or timeout doesn't end in lock errors.

**Screenshots**  
![grafik](https://user-images.githubusercontent.com/6271057/230740012-107ee3da-87e8-4f25-85f8-732dc4a33c81.png)

## Your setup
**Kirby Version**  
v3.9.3

**Console output**  
GEThttp://localhost/kirby/api/site/lock
[HTTP/1.1 403 Forbidden 970ms]

XHRGEThttp://localhost/kirby/api/site/lock
[HTTP/1.1 403 Forbidden 25ms]

**Your system (please complete the following information)**
WAMP setup

**Additional context**

**Comment by lukasbestle** [comment] 2023-04-08 20:22
The lock requests are not unnecessary. In fact, the Panel only gets to know that you have been logged out by the failing lock request. So to be honest I don't think we can solve this.

Even if we could: Were there any negative consequences for the user experience caused by the failed requests in particular that affected you?

**Comment by GiantCrocodile** [comment] 2023-04-08 20:31
Hi @lukasbestle! I thought these locks are used to prevent editing of same pages/users within a multi user setup, not for detecting whether you were signed out.

No, I didn't notice a negative impact for the user. I just reported it because I usually prefer a clean console approach to make debugging real issues easier.

**Comment by lukasbestle** [comment] 2023-04-08 20:45
Their main purpose is of course content locking. But as they are the only requests that happen automatically in the background, they are automatically the most likely to run into an expired user session.

So what I meant was not "lock requests are used to detect an expired session", more "an expired session can only be detected from failed requests, which most likely occurs with the background requests from content locking".

I'm closing this issue because we cannot avoid failed requests when a session expires as I explained.

**Closed as not planned by lukasbestle** 2023-04-08 20:45 UTC
