### ISSUE TITLE
[v4] Search in pages section with table layout throws JS error

### ISSUE THREAD

**Issue by JerikoOne** [k-next/kirby#5540] opened 2023-08-31 16:43 UTC
## Description
A pages section with table layout and enabled search throws a JS error upon entering a search term.

**Expected behavior**  
The pages section should be filtered and display only the valid results according to the search term.

**Screenshots**  
<img width="446" alt="image" src="https://github.com/getkirby/kirby/assets/3002580/3aaa3f0a-3520-464e-9cd9-5cf5f004421a">

## To reproduce
1. Create a blueprint that contains a pages section with table layout and enabled search
2. Create a page that is visible in that section
3. Try to search for the page
4. See error in dev console

## Your setup
**Kirby Version**  
4.0.0-alpha.7

**Console output**  
`Uncaught TypeError: this.pagination is undefined
    searchterm http://tinconwp.test/tincon23/media/panel/a704922e82e199553f378020dcb4a319/js/index.js:1
    n http://tinconwp.test/tincon23/media/panel/a704922e82e199553f378020dcb4a319/js/index.js:1
    setTimeout handler*bt/< http://tinconwp.test/tincon23/media/panel/a704922e82e199553f378020dcb4a319/js/index.js:1
    VueJS 12
    input http://tinconwp.test/tincon23/media/panel/a704922e82e199553f378020dcb4a319/js/index.js:1
    VueJS 4
    onInput http://tinconwp.test/tincon23/media/panel/a704922e82e199553f378020dcb4a319/js/index.js:1
    input http://tinconwp.test/tincon23/media/panel/a704922e82e199553f378020dcb4a319/js/index.js:1
    VueJS 33
[index.js:1:296817](http://tinconwp.test/tincon23/media/panel/a704922e82e199553f378020dcb4a319/js/index.js)
    searchterm http://tinconwp.test/tincon23/media/panel/a704922e82e199553f378020dcb4a319/js/index.js:1
    n http://tinconwp.test/tincon23/media/panel/a704922e82e199553f378020dcb4a319/js/index.js:1
    (Async: setTimeout handler)
    bt http://tinconwp.test/tincon23/media/panel/a704922e82e199553f378020dcb4a319/js/index.js:1
    VueJS 12
    input http://tinconwp.test/tincon23/media/panel/a704922e82e199553f378020dcb4a319/js/index.js:1
    VueJS 4
    onInput http://tinconwp.test/tincon23/media/panel/a704922e82e199553f378020dcb4a319/js/index.js:1
    input http://tinconwp.test/tincon23/media/panel/a704922e82e199553f378020dcb4a319/js/index.js:1
    VueJS 33`

**Your system (please complete the following information)**
 - Device: Macbook Pro M1 2020
 - OS: Ventura 13.3.1
 - Browser: Firefox
 - Version: 116
 
 **Additional info**
 The pages section shows the correct result when you interact with the pages in that section after searching for a term, e.g. reordering or renaming one.

**Comment by distantnative** [comment] 2023-08-31 16:45
Duplicate of https://github.com/getkirby/kirby/issues/5517

**Closed as completed by distantnative** 2023-08-31 16:45 UTC
