### ISSUE TITLE
[v4] Writer field: link dialog breaks when choosing file

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#5335] opened 2023-06-29 12:03 UTC
## Description
When I select text in a text block and try to add a link to a file the following error shows up.

**Screenshots**  
![Screenshot 2023-06-29 at 13 56 14](https://github.com/getkirby/kirby/assets/60777/6eb89b09-17ef-4bbf-b990-e72b484956bb)

## Your setup
**Kirby Version**  
4.0.0-alpha.3

**Console output**  
index.js:1 TypeError: Cannot read properties of null (reading 'label')
    at a.<anonymous> (index.js:1:283094)
    at t._render (vue.js:11:45499)
    at a.r (vue.js:11:79396)
    at t.get (vue.js:11:27998)
    at new t (vue.js:11:27911)
    at vue.js:11:79410
    at Cr.$mount (vue.js:11:79628)
    at Cr.$mount (vue.js:11:106970)
    at init (vue.js:11:33266)
    at vue.js:11:67703

**Comment by distantnative** [comment] 2023-06-29 14:28
Duplicate of https://github.com/getkirby/kirby/issues/5280 - will be fixed in alpha.4

**Closed as completed by distantnative** 2023-06-29 14:28 UTC
