### ISSUE TITLE
[Panel]: Overlay Background not removed when navigating away from the page while overlay is open

### ISSUE THREAD

**Issue by renestalder** [k-next/kirby#6623] opened 2024-08-16 14:20 UTC
## Description

Navigating away from overlays does not destroy the overlays properly. The background seems to stay.

Scenario 1: When a page section is rendered inside an overlay and the user clicks the page, the panel correctly navigates to the clicked page but doesn't remove all HTML properties of the overlay from the DOM. The alpha transparent background of the overlay is still visible until the user clicks on it.

Scenario 2: Opening an overlay and then clicking the browser back button.

**Expected behavior**  

Switch to another page by clicking a page in a pagelist rendered inside an overlay or pushing a browser navigation button should remove the complete overlay from the DOM.

## To reproduce

1. Go to the [online Kirby Demo](https://zone1.trykirby.com/EgTtzg8s/).
2. Go to a page that has a blocks field, like the blog.
3. Add a block like the image block, that has a configuration overlay.
4. After adding the block and the overlay for editing the image block is open, press the browser back button.
5. Now you still see the overlay background.

## Your setup
**Kirby Version**  

4.3.0

**Console output**  

No errors in the console.

**Your system (please complete the following information)**
 - Device: Mac Book
 - OS: macOs 14.6.0
 - Browser: Chromium (via Arc Browser)
 - Version: Based on Chromium version 127.0.6533.120

**Additional context**  

Problem not reproducible in an earlier version I upgraded from, 4.1.2.

**Comment by distantnative** [comment] 2024-08-16 14:37
Duplicate of https://github.com/getkirby/kirby/issues/6030 - will be fixed soon https://github.com/getkirby/kirby/pull/6620

**Closed as not planned by distantnative** 2024-08-16 14:37 UTC
