### ISSUE TITLE
k-models-dialog button margin missing when paginator shows

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#6015] opened 2023-11-28 16:04 UTC
## Description
<img width="347" alt="image" src="https://github.com/getkirby/kirby/assets/6684137/6bfbe6f9-61a6-446e-933a-881832265468">

**Expected behavior**  
<img width="353" alt="image" src="https://github.com/getkirby/kirby/assets/6684137/e44b1ece-3e4e-4f4d-8ebc-c1b8a512972a">

## To reproduce

1. have a page with more than 20 files
2. blueprint with a files field:
  ```yml
  fields:
    files:
      type: files
  ```
3. click on the select button
4. notice the missing margin between paginator and ok button

## Your setup
**Kirby Version**  
4.0.0

**Comment by distantnative** [comment] 2023-11-28 16:09
Duplicate of https://github.com/getkirby/kirby/issues/6010

**Closed as not planned** 2023-11-28 16:10 UTC
