### ISSUE TITLE
Panel: Opening main site page from breadcrumbs in new tab gives error page

### ISSUE THREAD

**Issue by neildaniels** [k-next/kirby#4244] opened 2022-03-30 17:43 UTC
## Description

If you Command-click or Right-Click > New Tab on the "root" of the top breadcrumbs in the Panel, it opens a URL that does not work on its own.

I think Kirby 3.6 is what originally broke this, but haven't confirmed when this stopped working.

**Expected behavior**  

Should be able to open the "site" in a new tab.

**Screenshots**  

<img width="406" alt="Screen Shot 2022-03-30 at 10 37 12 AM" src="https://user-images.githubusercontent.com/417182/160898119-8e97706e-6ebc-466f-9513-56ce7ddeed26.png">

<img width="504" alt="Screen Shot 2022-03-30 at 10 36 26 AM" src="https://user-images.githubusercontent.com/417182/160897035-dd3e147f-6eca-4e6d-b2cc-c7d75e039eaa.png">

## To reproduce

1. Open Panel
2. Click on some sub-page
3. Right click on the "site" in the Panel breadcrumbs and open in new site

The URL it tries to open resembles `http://localhost/panel/pages/site`.

However, if you're already on the Site page, the URL is `http://localhost/panel/site`.

It seems like there's an erroneous `/pages/` portion in the path. Normal clicking seems to be unaffected, as the Panel Javascript seems to correct for this issue.

## Your setup
**Kirby Version**  

`3.6.3.1`

**Console output**  

**Your system (please complete the following information)**
 - Device: Mac
 - OS: macOS
 - Browser: Safari
 - Version: 15.4 (17613.1.17.1.6)

**Additional context**

**Comment by afbora** [comment] 2022-03-30 18:32
What is your `base href` value/address for panel?

**Comment by neildaniels** [comment] 2022-03-30 20:01
The only Panel options in my config looks like this. And commenting this out completely seems to have no effect.

```php
    'panel' => [
        'css' => 'assets/css/panel.css',
    ],
```

However, my roots are definitely customized:
```php
<?php

use Kirby\Cms\App as Kirby;

$publicPath     = __DIR__;                      // /var/www/html/website/public
$websitePath    = dirname($publicPath);         // /var/www/html/website
$sitePath       = $websitePath . '/site';       // /var/www/html/website/site
$codePath       = dirname($websitePath);        // /var/www/html
$contentPath    = $websitePath . '/content';    // /var/www/html/website/content

require $codePath . '/kirby/bootstrap.php';

$kirby = new Kirby([
    'roots' => [
        'index'     => __DIR__,
        'base'      => $websitePath,
        'content'   => $contentPath,
        'site'      => $sitePath,
        'plugins'   => $sitePath . '/plugins-external', // `kirby-loader` plugin will load other plugins
        'public'    => $public = $websitePath . '/public',
        'assets'    => $public . '/assets',
        'media'     => $public . '/media',
        'storage'   => $storagePath = $websitePath . '/storage',
        'accounts'  => $storagePath . '/accounts',
        'cache'     => $storagePath . '/cache',
        'log'       => $storagePath . '/log',
        'sessions'  => $storagePath . '/sessions',
    ],
]);

echo $kirby->render();
```

Are there any other options you'd like to know? Happy to debug a bit more, but I don't know where the paths are being generated for the breadcrumbs (and why it only is an issue when you're on a sub-page).

I cannot reproduce this on the Kirby Demo site. I'm also on a multi-lang setup—maybe this is relevant?

**Comment by afbora** [comment] 2022-03-30 22:19
I can't still reproduce the issue. I'm not sure but I think this is related with your base href of panel. Because root site url is relative in breadcrumb. I'm guessing the base href value is not correct in your panel.

For example mine:

````html
<base href="/test/kirby/develop/panel/">
````

**Comment by neildaniels** [comment] 2022-03-30 23:22
Ah, sorry, I didn't realize you were talking about that value on the HTML page itself.

Mine is
```
<base href="/panel/">
```

However, I just noticed this in my Console:
```
Refused to change the document base URL to http://localhost/panel/ because it does not appear in the base-uri directive of the Content Security Policy.
```
<img width="894" alt="Screen Shot 2022-03-30 at 4 01 53 PM" src="https://user-images.githubusercontent.com/417182/160944755-51b2f167-bac8-4a3e-8e7b-a508e11d7c73.png">

And indeed, my CSP did include `base-uri 'none'`.

I've changed that to `base-url 'self'` and now it works fine.

**Comment by distantnative** [comment] 2022-03-31 15:30
@neildaniels so it was all due to the work Content policy?

**Comment by neildaniels** [comment] 2022-03-31 15:49
Yeah, the Content-Security-Policy was preventing the `base href` from taking effect. Once the policy change was adjusted, everything works fine.

I'm fine supporting closing this issue, unless you think something actionable should come out of this?

For example: I assume that the links _could_ be absolute links that would avoid having to needing to change the `base href` altogether. The JavaScript didn't seem to care that the `base href` modification didn't apply.

**Comment by bastianallgeier** [comment] 2022-04-06 11:12
I think we should close this. We didn't run into similar issues with the base href so far, but it's good to keep this in mind if it happens again. Thanks for taking the time to investigate.

**Closed as completed by bastianallgeier** 2022-04-06 11:12 UTC
Labels: needs: replication 🔬
