### ISSUE TITLE
[File Section] Allow to delete last file when min: 1 is set

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#4804] opened 2022-10-24 09:56 UTC
## Description

I added a files section with `min: 1` and `max: 1`. Once I added a file I can't remove it again.

**Expected behavior**  
I'd expect that I can remove the file to upload a new file. I can only replace it. In my current case I want to replace a png file with an svg file. Not possible :(

**Screenshots**  

![Screenshot 2022-10-24 at 11 52 07](https://user-images.githubusercontent.com/60777/197499745-f4a23ead-78e6-40a5-9d1d-d63ce9f47875.png)

## Your setup
**Kirby Version**  3.8.0

**Comment by afbora** [comment] 2022-10-24 10:51
@mrflix I just wonder that why don't you use files field with `required: true` and `multiple: false`?
https://getkirby.com/docs/reference/panel/fields/files

**Comment by mrflix** [comment] 2022-10-24 12:12
@afbora in this case it's just one image for the whole page. I could use a files field but that has the drawback that you can't delete files and might end up with the problem that you can't upload a file with the same filename. So I'd have to show the files section, too. I think just the files section is a better user experience.

**Comment by lukasbestle** [comment] 2022-10-30 21:31
@mrflix Do you need the `min: 1` prop for the files section? It doesn't trigger a validation error (preventing the page from being saved), so its only purpose (as far as I know) is just the red "invalid" border if no file is selected.

**Comment by mrflix** [comment] 2022-10-31 08:53
@lukasbestle Oh, you are right. I would have expected the `min: 1` to prevent the page from being saved.

Though still the red "invalid" border helps to remind the editor to add a file there.

**Comment by lukasbestle** [comment] 2022-10-31 21:12
Absolutely. I'm just thinking what the expected behavior should be.

A possible UX could be that sections become part of the form, so for example clicking on "Delete" for a file would not already delete the file, but stage it for deletion (meaning: an unsaved changes bar would appear and the deletion could still be discarded). With this behavior, deleting a file from a section with `min: 1` would work fine because the form could only be saved if there is a file in the section. Meaning: The user could either upload a new one or discard the change to keep the previous file.

However, in the current setup, deleting a file is permanent. So you could have the situation that the user deletes a file and leaves behind a broken setup. I think this is the reason why deleting files currently does not work if the section is already at its minimum.

Of course including sections in the form would be a pretty massive rewrite and would also come with many additional challenges. E.g. where to store uploaded files that are not yet saved, what about pages created from a section, is this even the right UX... But I feel like allowing the deletion of a required file would be a regression in some setups. I'd rather work towards allowing to replace a file with one of a different type/extension.

**Comment by distantnative** [comment] 2024-08-11 16:55
Closing this for now. We'll aim at some integration of sections and fields in the long run but for the moment changing the `min` behavior could lead to too many problems.

**Closed as not planned by distantnative** 2024-08-11 16:55 UTC
Labels: needs: discussion 🗣
