### ISSUE TITLE
Header buttons jump from right to left with long page titles

### ISSUE THREAD

**Issue by sebastiangreger** [k-next/kirby#6237] opened 2024-02-02 05:41 UTC
## Description
The header buttons (view, settings, status) in the panel do not remain adjusted to the right with long page titles:

![Screenshot from 2024-02-02 06-28-50](https://github.com/getkirby/kirby/assets/6355217/93119a05-24ab-4a22-b3e9-b83ba7206121)

![Screenshot from 2024-02-02 06-29-15](https://github.com/getkirby/kirby/assets/6355217/ec459e2f-5d3e-4063-80f9-4463e2762118)

## To reproduce
Create a page with a long title

## Your setup
K4.1.0
FF122.0 on Linux Mint

**Comment by afbora** [comment] 2024-02-02 09:23
@distantnative Is this related with https://github.com/getkirby/kirby/issues/5444?

**Comment by distantnative** [comment] 2024-02-02 11:21
No, that was just about dropdown position.

But it's a duplicate of https://github.com/getkirby/kirby/issues/5438

**Closed as not planned by distantnative** 2024-02-02 11:21 UTC
